name: Pull Request Checks

on:
  pull_request:
    branches: [ main ]

jobs:
  quick-checks:
    name: Quick Checks
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v4

    - name: Set up Python 3.10
      uses: actions/setup-python@v4
      with:
        python-version: '3.10'
        cache: 'pip'

    - name: Verify Python version
      run: |
        python --version
        python -c "import sys; print(f'Python version: {sys.version}')"

    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip setuptools wheel
        pip install flake8 mypy  # Removed black since format check is disabled
        pip install -r requirements.txt
        pip install -e .

    - name: Lint check
      run: |
        flake8 icenet/ scripts/ tests/ --count --select=E9,F63,F7,F82 --show-source --statistics

    # - name: Format check
    #   run: |
    #     black --check icenet/ scripts/ tests/

    - name: Type check
      run: |
        mypy icenet/ --ignore-missing-imports

    - name: Import test
      run: |
        python -c "import icenet; print('Import successful')"

  test-core:
    name: Test Core Functionality
    runs-on: ubuntu-latest
    needs: quick-checks

    steps:
    - uses: actions/checkout@v4

    - name: Set up Python 3.10
      uses: actions/setup-python@v4
      with:
        python-version: '3.10'
        cache: 'pip'

    - name: Verify Python version
      run: |
        python --version
        python -c "import sys; print(f'Python version: {sys.version}')"

    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install pytest-cov coverage  # Added coverage tools
        pip install -r requirements.txt
        pip install -e .[dev]

    - name: Run tests
      run: |
        python -m pytest tests/ -v --tb=short --cov=icenet --cov-report=term --cov-report=xml

    - name: Coverage Summary
      run: |
        pip install coverage
        coverage report --show-missing

    - name: Upload coverage to Codecov
      uses: codecov/codecov-action@v4
      with:
        file: ./coverage.xml
        flags: pr-tests
        name: pr-coverage

    - name: Coverage comment
      uses: py-cov-action/python-coverage-comment-action@v3
      with:
        GITHUB_TOKEN: ${{ github.token }}
        MINIMUM_GREEN: 80
        MINIMUM_ORANGE: 70

    - name: Test training pipeline
      run: |
        python scripts/train.py --create-data --config configs/config.yaml

  security-check:
    name: Security Check
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v4

    - name: Set up Python 3.10
      uses: actions/setup-python@v4
      with:
        python-version: '3.10'
        cache: 'pip'

    - name: Verify Python version
      run: |
        python --version
        python -c "import sys; print(f'Python version: {sys.version}')"

    - name: Install security tools
      run: |
        python -m pip install --upgrade pip
        pip install bandit safety
        pip install -r requirements.txt

    - name: Run security checks
      run: |
        bandit -r icenet/ || true
        safety check || true
